[project]
name = "ex05-ml-prediction-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.0",
    "pyarrow>=23.0.0",
    "s3fs>=2026.2.0",
    "scikit-learn>=1.8.0",
]
